server:
  port: 8091

spring:
  application:
    name: music-test
  data:
    mongodb:
      host: #your ip#
      port: 27017
      database: myTest
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200