alibaba:
  cloud:
    access-key:
    secret-key: #阿里云获取#
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com
      bucket: bleuweb-music
      callbackUrl: http://localhost:8082/oss/callback

server:
  port: 8089

spring:
  cloud:
    nacos:
      discovery:
        server-addr: #ip#:8848
  application:
    name: music-upload
logging:
  config: classpath:log4j2.xml



