server:
  port: 8084
spring:
  mail:
    host: smtp.163.com
    username: mashinas@163.com
    password:
    port: 25
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
        transport:
          protocol: smtp
  application:
    name: musicMail
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848